### PR TITLE
Increase timeout when waiting for a transaction to be signed

### PR DESCRIPTION
**Pull request by gilmeir-arnac**
## Description
When doing manual approval the existing 20s timeout may not be enough, so increasing the polling timeout. Later we would add it to the config to allow users to control it.

## Ticket
[DEV-15865](https://fordefi.atlassian.net/browse/DEV-15865)

- - -
This change is [Reviewable](https://reviewable.io/reviews/FordefiHQ/web3-provider/14)

### CODE REVIEW

**Review by rony-arnac — CHANGES_REQUESTED** [review]
> Reviewed 5 of 5 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FordefiHQ/web3-provider/14)* status: all files reviewed, 1 unresolved discussion (waiting on @gilmeir-arnac)

___
*[`src/utils/transactions.ts` line 212 at r1](https://reviewable.io/reviews/FordefiHQ/web3-provider/14#-O6Lmc_C8O0aOXgk0muv:-O6Lmc_C8O0aOXgk0muw:busk1jn) ([raw file](https://github.com/FordefiHQ/web3-provider/blob/67cadd3c7b760809ef95dd4f3da8c742037d1829/src/utils/transactions.ts#L212)):*
> ```XML
>   apiClient: ApiClient,
>   timeoutDurationMs: number,
>   pollingIntervalMs: number,
> ```

convert to interface... too many props



_Code quote:_
```XML
  { id: transactionId }: T,
  desiredState: EvmTransactionState,
  apiClient: ApiClient,
  timeoutDurationMs: number,
  pollingIntervalMs: number,
```

**Review by gilmeir-arnac — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/FordefiHQ/web3-provider/14)* status: 3 of 585 files reviewed, 1 unresolved discussion (waiting on @rony-arnac)

___
*[`src/utils/transactions.ts` line 212 at r1](https://reviewable.io/reviews/FordefiHQ/web3-provider/14#-O6Lmc_C8O0aOXgk0muv:-O6WD2M5CUuEpPyTA3l9:b-896fix) ([raw file](https://github.com/FordefiHQ/web3-provider/blob/67cadd3c7b760809ef95dd4f3da8c742037d1829/src/utils/transactions.ts#L212)):*
<details><summary><i>Previously, rony-arnac (Rony Fragin) wrote…</i></summary><blockquote>

convert to interface... too many props
</blockquote></details>

Done.

**Review by rony-arnac — APPROVED** [review]
> Reviewed 582 of 582 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FordefiHQ/web3-provider/14)* status: all files reviewed, 1 unresolved discussion (waiting on @gilmeir-arnac)

___
*[`src/provider/provider.ts` line 325 at r2](https://reviewable.io/reviews/FordefiHQ/web3-provider/14#-O6WE830-mrnva_TzDd4:-O6WE830-mrnva_TzDd5:b-6ru1uq) ([raw file](https://github.com/FordefiHQ/web3-provider/blob/0e6bcf45af79e10551082ff669ca7b637af29cb5/src/provider/provider.ts#L325)):*
> ```XML
> 
>     return waitForTransactionState({
>       transaction: transaction as AnyEvmTransaction<CreateTxType>,
> ```

can do satisfies?

**Review by rony-arnac — APPROVED** [review]
> Reviewed 3 of 3 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/FordefiHQ/web3-provider/14)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @gilmeir-arnac)

**Pull request merged**
